### ISSUE TITLE
📲 Improve responsiveness

### ISSUE THREAD

**Issue by reneaaron** [getAlby/lightning-browser-extension#1950] opened 2023-01-07 16:35 UTC
### Feature description

Alby is currently not optimized for usage on smaller screens such as on mobile phones. Browsers with extension support (such as Kiwi Browser) potentially allow users to use Alby on their mobile devices, too.

### Navigation

Discover, Websites, Send & Receive are too wide and break the overall layout. 

![image](https://user-images.githubusercontent.com/100827540/211160111-8d28d43d-4aa2-441f-b7ec-9094419ec586.png)

### Onboarding

Optimize for mobile views:

![image](https://user-images.githubusercontent.com/100827540/211161023-b1f64a5b-825c-4053-97af-6e423ad0d281.png)

![image](https://user-images.githubusercontent.com/100827540/211161029-6ae42f71-a68e-46c2-bd0f-5b9598d8426c.png)

### Body height

Seems not to use the full height. Also transaction lists are cut off at the bottom of the bottom of the button.

![image](https://user-images.githubusercontent.com/100827540/211160980-2f1ad94e-2d55-417e-8ad0-15306b057c84.png)

**Comment by rolznz** [comment] 2023-01-12 07:07
https://github.com/getAlby/lightning-browser-extension/pull/1969 solves the connection / onboarding issues. 

I cannot reproduce or test the body height issue, can this be fixed in a separate PR?

**Comment by rolznz** [comment] 2023-01-12 07:11
Other places I noticed:
- Nostr key in settings
![image](https://user-images.githubusercontent.com/33993199/212000676-f1390e41-2f12-4762-8219-9bbb97b47f5c.png)
- Discover cards are too tall 
![image](https://user-images.githubusercontent.com/33993199/212000862-6bef35d7-1053-4948-a025-dda84ec5d9e5.png)

**Closed** 2023-01-15 12:41 UTC
Labels: idea
