### ISSUE TITLE
After creating an Alby wallet a message about connected node appears

### ISSUE THREAD

**Issue by AnastasiaVolk** [getAlby/lightning-browser-extension#1262] opened 2022-08-09 21:31 UTC
**Description:**
After creating an Alby wallet a message about connected node appears

![Image](https://user-images.githubusercontent.com/108762093/183530040-6c34a7bc-2bca-42ca-a16c-a8fdcde4304f.png)

**Steps to reproduce the behaviour:**

1. Visit to getalby.com
2. Click on "Install Alby"
3. Click "Add extension to Chrome"
4. Click "Get started"
5. Input a password
6. Confirm a password
7. Click "Next"
8. Input new email
9. Input correct password
10. Click “Continue”

**Alby information**

Alby Version: [v1.13.0]
Alby installed through Google Chrome

**Device information:**

OS: [macOS Monterey 12.0.1 ] 
Browser [chrome]  Browser Version [Chrome Version 103.0.5060.114]

**Are you working on this issue?**

No

**Comment by escapedcat** [comment] 2022-08-10 01:18
Would be great to stick to our issue template. Without "Expected behavior" we don't know what should be fixed how or by who.
The current description isn't a bug it's intended behaviour. I understand that this might not be optimal and should be changed but then we need to adjust this issue I believe.

**Comment by AnastasiaVolk** [comment] 2022-08-10 10:47
I'm not giving a bug label here or give bug description. it is just confusing it is saying about node after the user just created a wallet... Expected behaviour here is just something like "Now you've created your wallet would you like to go through tutorial?" instead of "Now you've connected your node would you like to go through tutorial?"

**Comment by escapedcat** [comment] 2022-09-12 10:14
Will be done with #981

**Closed** 2022-10-03 10:59 UTC
Labels: idea
