### ISSUE TITLE
Add feedback when users attempts to signup with already used email

### ISSUE THREAD

**Issue by secondl1ght** [getAlby/lightning-browser-extension#703] opened 2022-03-17 19:29 UTC
**Is your feature request related to a problem? Please describe.**
We should add some better user feedback when a user tries to signup with an email that is already been used.

**Describe the solution you'd like**
Currently when you enter an email that has already been used this is the error you get:

![image](https://user-images.githubusercontent.com/85003930/158880722-fa66f08f-e8db-4470-8e0d-eec8750efd46.png)

It is not very helpful so we should add some feedback directly on the page with more info.

**Are you working on this? (Yes/No)**
I could work on this.

**Comment by pavanjoshi914** [comment] 2022-03-19 10:20
duplicate of https://github.com/getAlby/lightning-browser-extension/issues/650

**Comment by im-adithya** [comment] 2022-03-19 12:59
Can I work on this?

**Comment by escapedcat** [comment] 2022-03-19 13:08
@im-adithya there no existing PR for this but @secondl1ght already indicated he's interested.
@secondl1ght wanna hand this over?

**Comment by secondl1ght** [comment] 2022-03-20 03:21
Didn't realize this was a duplicate - let's keep this one open because it tracks the email issue specifically where the other issue tracks other errors as well. But @pavanjoshi914 can you update the other issue with the other examples of errors you would like to see improved on?

And @im-adithya sure you can work on this if you would like. Thanks 👍🏼

**Comment by pavanjoshi914** [comment] 2022-03-20 04:10
> Didn't realize this was a duplicate - let's keep this one open because it tracks the email issue specifically where the other issue tracks other errors as well. But @pavanjoshi914 can you update the other issue with the other examples of errors you would like to see improved on?
> 
> And @im-adithya sure you can work on this if you would like. Thanks 👍🏼

sure

**Comment by im-adithya** [comment] 2022-03-20 12:25
> Didn't realize this was a duplicate - let's keep this one open because it tracks the email issue specifically where the other issue tracks other errors as well. But @pavanjoshi914 can you update the other issue with the other examples of errors you would like to see improved on?
> 
> And @im-adithya sure you can work on this if you would like. Thanks 👍🏼

Welcome! Opened #712 for this!

**Closed** 2022-05-10 08:20 UTC
