### ISSUE TITLE
[Feature] Split nostr signing permission

### ISSUE THREAD

**Issue by rolznz** [getAlby/lightning-browser-extension#2664] opened 2023-08-13 06:39 UTC
### Feature description

There is only one nostr signing permission, which gives the user no control over what is signed if they enable it

If I make Alby remember to sign app-specific data (a specific "kind") on primal.net, now it can sign any message which I do NOT want.

![image](https://github.com/getAlby/lightning-browser-extension/assets/33993199/4586e916-81aa-47f1-aeac-59ebb2e2a173)

### Describe the solution

Signing permissions should be based on kinds, I guess?

### Are you working on this?

None

**Comment by reneaaron** [comment] 2023-09-04 11:27
Closing as duplicate of #2698. Thanks for raising it @rolznz! :raised_hands:

**Closed by reneaaron** 2023-09-04 11:27 UTC
Labels: idea

**Comment by rolznz** [comment] 2023-09-04 15:02
Note: I believe this is slightly different than the other ticket. That one would allow the website to request in advance all the permissions it needs.

Here, we are just making the nostr signing permission more refined - allowing to remember a specific kind rather than all the kinds.

**Comment by reneaaron** [comment] 2023-09-05 06:27
@rolznz I've enhanced the scope of the other issue to include the more refined permissions. (see the screenshot in my last post)
