### ISSUE TITLE
Implement error bar when Alby cannot reach connected node

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/lightning-browser-extension#2499] opened 2023-06-20 23:49 UTC
Currently, when Alby cannot reach node following flow happens:

**1. There's skeleton in the account bar indicating that Alby is trying to reach a node**
<img width="434" alt="Screenshot 2023-06-21 at 01 41 37" src="https://github.com/getAlby/lightning-browser-extension/assets/68239231/83b80de4-79a6-4676-b981-d74ba512834f">

**2. Error toast message is displayed after timeout**
<img width="421" alt="Screenshot 2023-06-21 at 01 41 21" src="https://github.com/getAlby/lightning-browser-extension/assets/68239231/279c2597-4689-4315-b35a-93ebe66f8745">

**3. After that there's no indication there is a problem. Balance is still displayed** (which may be incorrect!)
<img width="411" alt="Screenshot 2023-06-21 at 01 41 29" src="https://github.com/getAlby/lightning-browser-extension/assets/68239231/bccf8aaa-111c-4644-95ac-c8c66f2db6eb">

We'd like to introduce an error bar / notification that appears at the step 3. This will should be also displayed in the accounts dropdown, and stay in that state until the connection is successful again ([Figma file here](https://www.figma.com/file/AMzMvcwrr2IdunqMakaB8r/navigation%2C-dropdown%2C-receive-onchain-work%2C-connectors%2C-nostr-events?type=design&node-id=653-33562)):

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/ad46806b-c612-4101-bb65-3bf03d64061b)

--- 

# Handoff 

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/f3357627-0c74-4ff3-9d62-8a40976145e4)

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/c36650b7-f0a4-4c60-a81f-d8cda29e424e)

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/1daac68f-a91e-4c1c-9c37-46035c56b531)

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/b65ecd89-4682-42d9-9bfc-33ab8aca6d17)

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/1d1eef6f-bc27-4306-bb58-43f88aaa8501)

![image](https://github.com/getAlby/lightning-browser-extension/assets/68239231/33fd52cb-38cf-4b87-b83c-49a6c2de4076)

**Comment by rolznz** [comment] 2023-06-21 04:47
@stackingsaunter does it make sense to only have a small error bar and still show the old state and send/receive buttons (which won't work)? 

I think it might be better to have a full error screen with a refresh button. Otherwise we need to individually block all the functionality of different buttons (send, receive, etc). 

Related to https://github.com/getAlby/lightning-browser-extension/issues/2468 

CC @reneaaron

**Comment by lujakob** [comment] 2023-06-21 10:57
Seems like a duplicate of #2377 I am waiting to merge #2456 before I can continue it.

@rolznz mentioned #2468 - seems like we have a couple of similar related issues/ideas about this now?

**Comment by stackingsaunter** [comment] 2023-06-21 14:18
@lujakob thanks I missed that. Closing this and let's continue in #2377

**Closed** 2023-06-21 14:25 UTC
Labels: good first issue, frontend
