### ISSUE TITLE
[BUG] I should be able to LNURL login with Alby even if my Umbrel node be offline

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#1690] opened 2022-10-29 19:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm having problems with my Umbrel node but I used it with Alby to authenticate on some services using LNURL-AUTH. Now I'm unable to login in these services.

### Steps To Reproduce

1- Disconnect Umbrel node
2- Try to use Alby to login on sites you previously logged using lnurl-auth 

### Expected behavior

I would expect Alby save locally the key from my Umbrel so I could still login on sites even if my Umbrel node be disconnected.

### Alby information

Alby version: 1.18

### Are you working on this?

No

**Comment by bitcoinuser** [comment] 2022-10-29 20:07
Related to this issue: https://github.com/getAlby/lightning-browser-extension/issues/802

**Comment by reneaaron** [comment] 2022-11-05 09:46
Closing as a duplicate of #802. 

We can't fix this unless we choose to move signing to a separate signing key that you can manage inside of Alby.

**Closed by reneaaron** 2022-11-05 09:46 UTC
