### ISSUE TITLE
On send window, show a list of lightningaddress from previous payments I did

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#1498] opened 2022-09-21 14:37 UTC
### Is your feature request related to a problem?

I want an easy way to send sats to a ln-address I used before. Currently I need to paste or type it in all the time.

### Describe the solution you'd like

When I click on send window, I would like to see a list of all lightningaddress that I already sent payments in the past. So I will not need to type the lightningaddress all times I want to send a payment to a friend.

![Captura de tela de 2022-09-21 11-28-24](https://user-images.githubusercontent.com/1178856/191533620-b893a604-985b-48c3-9200-8d714f777851.png)

**Comment by escapedcat** [comment] 2022-09-28 08:20
Maybe related to https://github.com/getAlby/meta/issues/15

**Comment by manavdesai27** [comment] 2023-02-16 19:29
How would we save the paid accounts list? Locally in cache or in database? @escapedcat

**Comment by escapedcat** [comment] 2023-02-18 16:26
I think this issue is being tackled via #1965 already

**Comment by stackingsaunter** [comment] 2023-07-26 13:07
Closing as it's a duplicate of #1971 
Contact list is a bit more complex, autosuggestions could be first step

**Closed by stackingsaunter** 2023-07-26 13:07 UTC
Labels: enhancement, frontend
