### ISSUE TITLE
Connection failed. i(...).runtime.connectNative is not a function

### ISSUE THREAD

**Issue by n-e-t-d-i-v-e-r** [getAlby/lightning-browser-extension#649] opened 2022-03-02 14:00 UTC
**Describe the bug**
I’ll trying to connect my private lightning-node with alby but after I inserted all credentials I copied from zeus-wallet (where my fullnode also is connected) I get alert mentioned in the ticket title.

**To Reproduce**
At last step from the onBoarding process in BraveBrowser.

**Expected behavior**
OnBoarding will ending as expected and I can use Alby with my own lnd-fullnode on my Raspibolt.

**Information About Alby**
- Alby Version:  1.5.0
- Alby installed through the browser store
- Wallet connected LND

**Screenshots (If Any)**
<img width="930" alt="Screenshot 2022-03-02 at 14 52 19" src="https://user-images.githubusercontent.com/87816768/156375950-574c05c9-bf9b-418a-a321-4bca329be52f.png">

<img width="797" alt="Screenshot 2022-03-02 at 15 18 12" src="https://user-images.githubusercontent.com/87816768/156379246-67c181cf-843f-4aaf-9ad3-a3174b374cff.png">

**Device Information [optional]:**
 - MacOS
 - Brave
 - 1.31.87

**Comment by escapedcat** [comment] 2022-03-03 02:16
Is this an Onion-Address? I'm not sure if this is supported right now. Is it @bumi ?

**Comment by n-e-t-d-i-v-e-r** [comment] 2022-03-03 05:39
yes it is. so that means I don’t have a chance to install alby on my website until you implement more privacy? thx for your answer and hope you will support onion-addresses soon.

**Comment by escapedcat** [comment] 2022-03-03 07:22
> maybe it is a good idea to inform on your homepage, that onion-addresses won’t work so far ...

Agreed. Let's wait till bumi confirmed or denied this and update readme and maybe roadmap (if existing).

**Comment by n-e-t-d-i-v-e-r** [comment] 2022-03-03 12:37
OK. if it isn’t implemented yet I would suggest this as a feature request. 😜

**Comment by bumi** [comment] 2022-03-04 15:22
Thanks for this issue and sorry that you ran into this. 
Tor connections are a bit tricky because the browsers do not natively support Tor. You would need to run Tor on you computer and proxy all requests through it. Because this is annoying and too complicated we have built an Alby app to support nodes behind Tor. 

This is currently in the release process and the extension does not yet check if this App is available - it just assumes it is there. That's why you run into this issue.
In the upcoming release this should be fixed and you will get a nice message to download that Tor support. 

Until then:
* Download the Alby app for macOS: https://github.com/getAlby/alby-installer-macos/releases/download/v1.0.2/Alby.zip
* Run the app and install it for your browser

It would be super amazing if you can help testing this setup and let us know if this works for you.

**Comment by n-e-t-d-i-v-e-r** [comment] 2022-03-05 07:44
thx for your response. but unfortunately I’ll get the same message after double clicking the downloaded item:
<img width="1044" alt="Screenshot 2022-03-05 at 08 31 59" src="https://user-images.githubusercontent.com/87816768/156873808-cc4bccd8-ba55-4eaa-92c3-352e79145475.png">

<img width="979" alt="Screenshot 2022-03-05 at 08 28 38" src="https://user-images.githubusercontent.com/87816768/156873809-1b0e478d-afe7-4d73-8aa6-905ec429f177.png">

did I something wrong by the install of the downloaded file? should I install it different as in the chrome appstore, as example upload it in some repository?

**Comment by n-e-t-d-i-v-e-r** [comment] 2022-03-05 07:51
thx for your response. but unfortunately I’ll get the same alert after installing alby over the downloaded file:
<img width="1044" alt="Screenshot 2022-03-05 at 08 31 59" src="https://user-images.githubusercontent.com/87816768/156874089-1fbbcb9d-a3af-41d4-8308-c2e9ac4f2b5b.png">

<img width="1117" alt="Screenshot 2022-03-05 at 08 48 59" src="https://user-images.githubusercontent.com/87816768/156874095-bb123c05-7e47-4248-ab92-2cfddbc1227a.png">

did I something wrong with the installing process? should I upload it in some repository instead of klick the install-button on your homepage after klicking install on the downloaded app?

**Comment by bumi** [comment] 2022-03-05 09:55
hmm. thanks for testing. did you restart brave? or can you try restarting it?

**Comment by n-e-t-d-i-v-e-r** [comment] 2022-03-05 10:15
after restart I’ll get this
<img width="976" alt="Screenshot 2022-03-05 at 11 12 21" src="https://user-images.githubusercontent.com/87816768/156878879-cd87fb65-c66d-45a8-9eea-73708f347136.png">

but that’s strange. because I copied the credentials out from my zeus-lnd-raspibolt configuration and zeus-wallet works perfect with it ...

**Comment by bumi** [comment] 2022-03-05 10:18
ok, interesting. thanks so much for helping debugging! :) 
in the address do you have the port there? (our explanation is not really good there in the current version) 
so it should be something like: 
`https://xxxx.onion:8080`

**Comment by n-e-t-d-i-v-e-r** [comment] 2022-03-05 10:25
same result ...
MacOS: 12.0.1
Brave Version: 1.32.115

**Comment by bumi** [comment] 2022-03-05 10:41
ok, any chance you can try Firefox? to identify if it is Brave related or generally. 
if you want we can also chat on Telegram or somewhere else.

**Comment by n-e-t-d-i-v-e-r** [comment] 2022-03-05 11:40
SUCCESS!
with firefox it went well and easy going
<img width="1254" alt="Screenshot 2022-03-05 at 11 52 05" src="https://user-images.githubusercontent.com/87816768/156881399-65eb7337-c3e4-402f-aee3-fe4fd71891ba.png">

but where does this sats coming from? now i have to try to connect my website with this and testing how it works. what should change on my website and where will I find this alby-integration?

**Comment by n-e-t-d-i-v-e-r** [comment] 2022-03-05 11:47
btw: we can communicate for sure on telegram, what’s your chat room there?

**Comment by n-e-t-d-i-v-e-r** [comment] 2022-03-05 11:53
next «issue». where can I configure my hompage to receive sats from visitors?
<img width="1263" alt="Screenshot 2022-03-05 at 12 51 17" src="https://user-images.githubusercontent.com/87816768/156881848-14ec914a-5902-4b6c-8b0f-2f6ae4367597.png">

**Comment by bumi** [comment] 2022-03-05 11:56
great! so I have to look into Brave and what's different there. 

so you now have Alby connected to your Umbrel node and can directly send/receive Sat from your browser. 
This works best on [WebLN](https://webln.dev/) enabled websites. [https://makers.bolt.fun/](https://makers.bolt.fun/) is a directory with some examples. 
You can also send Sat to users that have lightning details on their Twitter profile, or in YouTube videos etc. (e.g. https://twitter.com/dergigi or https://www.youtube.com/c/KoreacomK ) 


To receive Sat on your website you have to add lightning details to the HTML of your website: https://getalby.com/value4value 
For example https://nodesignal.space/ did this. It is a simple HTML meta tag that you need to add. 
This meta tag then tells a visitor with Alby where the Sat can be sent to. 

Do you have a lightning address already?

**Comment by n-e-t-d-i-v-e-r** [comment] 2022-03-05 12:00
to be honest, I’m not sure. I’m new on lightning, but I have a lightning fullnode running on my raspibolt so I think I will find this lightning address somwhere in ride the lightning?

**Comment by n-e-t-d-i-v-e-r** [comment] 2022-03-05 12:06
btw: my website is an wordpress-blog-page and I would connect alby with all blog-posts on this URL: www.bitpartikel.com <http://www.bitpartikel.com/> and all sub URL. should i add on every single link this «simple HTML tag»?

**Comment by n-e-t-d-i-v-e-r** [comment] 2022-03-05 12:11
and btw where to find and how to integrate this?
<img width="237" alt="Screenshot 2022-03-05 at 13 09 41" src="https://user-images.githubusercontent.com/87816768/156882416-fc46fa6f-4689-40ec-8a65-d0a89fba2c96.png">

**Comment by n-e-t-d-i-v-e-r** [comment] 2022-03-05 13:44
does this also works with an LNURL wallet?

**Comment by MoritzKa** [comment] 2022-03-05 13:49
may I ask where did you find this picture? 
We created several of these icons. You can download them here: https://github.com/getAlby/media/tree/main/Alby-tipping-buttons

I guess you have to put the meta tag on each page of your website where you want to receive sats. 
A Lightning address is based on LNURL and this lightning address is what you need for your meta tag. 

You can get one here: https://getalby.com/lightning-address . You can connect your own node to it and soon nodes behind TOR.
These videos describe how it works.

**Comment by n-e-t-d-i-v-e-r** [comment] 2022-03-05 14:05
sry. last try. which videos? I think I will give up and goes for a walk now … ;O)

**Comment by MoritzKa** [comment] 2022-03-05 14:21
No worries. The videos are linked in last line of my comment above or here: https://www.youtube.com/channel/UCIICdm6mox3VkCAv-yHMeMw/videos
Happy to give you a walk through the portal. just ping me moritz@getalby.com. 
Ich finde die Artikel auf deiner Seite klasse. We should get this going.

**Closed** 2022-03-06 10:05 UTC

**Comment by n-e-t-d-i-v-e-r** [comment] 2022-03-06 10:07
alby is not yet integrated on my website as desired, but could at least be installed in the browser. therefore i am closing this ticket.
