### ISSUE TITLE
[BUG] Click on close x icon on change unlock password, doesn't close the window

### ISSUE THREAD

**Issue by bitcoinuser** [getAlby/lightning-browser-extension#2221] opened 2023-03-15 21:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Click on close x icon on change unlock password, doesn't close the window. See the video:

https://user-images.githubusercontent.com/1178856/225449964-fcee4506-78e0-4f55-a31a-a4b3a0c296d7.mp4

### Steps To Reproduce

1- Go to change unlock password
2- Click on X close icon

### Expected behavior

Close the window. But now needs too clicks to close the window.

### Alby information

Alby: 1.28.1

### Are you working on this?

No

**Comment by Tejasp2003** [comment] 2023-03-16 10:50
I checked the issue. It will get closed, if you click again on the X icon

**Comment by escapedcat** [comment] 2023-03-16 11:48
Clicking the "x" should not submit the form and trigger the validation

**Comment by soham4abc** [comment] 2023-03-16 12:47
I would like to work on this issue.

**Comment by Tejasp2003** [comment] 2023-03-16 12:54
I am working on it

**Comment by SveeJ** [comment] 2023-03-29 12:26
Has this issue been fixed? If not, could I be assigned this Issue?

**Comment by Tejasp2003** [comment] 2023-03-29 12:53
No, i will not be able to contribute for a month due to college exams

**Comment by escapedcat** [comment] 2023-03-29 12:56
@soham4abc you also asked, you still up for it?

**Comment by soham4abc** [comment] 2023-03-29 12:58
> @soham4abc you also asked, you still up for it?

As @Tejasp2003 is not working on it I can give it a try!

**Comment by henriq4** [comment] 2023-04-07 18:54
Hey @escapedcat! I have been researching the code to identify the cause of the error and have found that the issue occurs when the focus is automatically on the input and is removed (such as when closing the modal), triggering error checks. Although this behavior is expected and not a bug, it can still lead to a poor user experience.

As a solution, I have made modifications to the component to prevent this issue from occurring in the future. I plan to submit a pull request with more details. As there haven't been any updates on this issue, could you please assign it to me?

**Comment by henriq4** [comment] 2023-04-07 18:56
Hey @escapedcat! I have been researching the code to identify the cause of the error and have found that the issue occurs when the focus is automatically on the input and is removed (such as when closing the modal), triggering error checks. Although this behavior is expected and not a bug, it can still lead to a poor user experience.

As a solution, I have made modifications to the component to prevent this issue from occurring in the future. I plan to submit a pull request with more details. As there haven't been any updates on this issue, could you assign it to me?

**Comment by legendarykamal** [comment] 2023-04-09 11:47
Hi , I am willing to work on this issue Have done the project setup.  Can I please get assigned ?

**Comment by henriq4** [comment] 2023-04-09 15:48
Hi @legendarykamal! I am working on it.

**Comment by reneaaron** [comment] 2023-09-01 12:27
This has been fixed in a recent release! :partying_face:

**Closed by reneaaron** 2023-09-01 12:27 UTC
Labels: bug, good first issue
