### ISSUE TITLE
Add support for lndconnect URLs

### ISSUE THREAD

**Issue by bumi** [getAlby/lightning-browser-extension#261] opened 2021-10-06 16:10 UTC
lnd connect describes a URL that contains all need information to connect to an lnd node.

it uses the `lndconnect:` scheme. 
We should add support for those links and automatically prefill the connector setting to make it easy for users to add an LND connection.

https://github.com/LN-Zap/lndconnect/blob/master/lnd_connect_uri.md

**Comment by secondl1ght** [comment] 2021-11-02 03:13
Wouldn't mind doing some pair programming on this if anyone is interested.

**Comment by AaronDewes** [comment] 2022-02-13 09:26
I basically got this working, but the problem is that most LND nodes (like Umbrel) use TLS with a self-signed certificate. There is no way in the fetch API to ignore the certificate errors from this AFAIK. I think it would ork over Tor. I'll open a draft PR soon, maybe someone has an idea.

**Comment by bumi** [comment] 2022-02-14 11:37
ah true. 
Sadly we have to rely on the browser for the certificates. This means similar to Tor requests can be made through the native companion app, OR: 
an exception has to be added or the certificate has to be added to the browser. 
Mostly it should be actually enough to open the URL once manually and add an exception. 

for loading lndconnect strings we should probably ignore the certificate for now.

**Comment by stackingsaunter** [comment] 2023-03-16 13:29
I believe this is implemented already, so closing

**Closed by stackingsaunter** 2023-03-16 13:29 UTC
Labels: duplicate, enhancement
